### ISSUE TITLE
Unable to run `nvidia-smi` on p28xYY instances after reboot

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#733]
```
# nvidia-smi 
Failed to initialize NVML: Driver/library version mismatch
```

**Comment by tschaffter** [comment]
As I observed, reinstalling the driver solves the issue. Same comment in the article below:
http://christopher5106.github.io/nvidia/2016/12/30/commands-nvidia-install-ubuntu-16-04.html

**Comment by tschaffter** [comment]
p28x20, which was instantiated last week has the same issues.

Installed on p28x20 the latest NVIDIA drivers:
http://us.download.nvidia.com/XFree86/Linux-x86_64/375.39/NVIDIA-Linux-x86_64-375.39.run
Before that, the version used was 367.48 and CUDA 8.0, V8.0.44.
CUDA is automatically up to date using `yum` (current version is 8.0, V8.0.44). cuDNN is already the latest version.

However the issue persists: reboot and then `nvidia-smi` returns the mismatch error.

**Comment by tschaffter** [comment]
```
# dmesg | grep -i nvidia
[3608956.820315] nvidia: loading out-of-tree module taints kernel.
[3608956.820316] nvidia: loading out-of-tree module taints kernel.
[3608956.820317] nvidia: loading out-of-tree module taints kernel.
[3608956.820318] nvidia: loading out-of-tree module taints kernel.
[3608956.820320] nvidia: loading out-of-tree module taints kernel.
[3608956.820321] nvidia: loading out-of-tree module taints kernel.
[3608956.820322] nvidia: loading out-of-tree module taints kernel.
[3608956.820323] nvidia: loading out-of-tree module taints kernel.
[3608956.820324] nvidia: module license 'NVIDIA' taints kernel.
[3608956.820325] nvidia: module license 'NVIDIA' taints kernel.
[3608956.820326] nvidia: module license 'NVIDIA' taints kernel.
[3608956.820327] nvidia: module license 'NVIDIA' taints kernel.
[3608956.820329] nvidia: module license 'NVIDIA' taints kernel.
[3608956.820330] nvidia: module license 'NVIDIA' taints kernel.
[3608956.828867] nvidia: module verification failed: signature and/or required key missing - tainting kernel
[3608956.903862] nvidia-nvlink: Nvlink Core is being initialized, major device number 248
[3608956.910173] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  367.48  Sat Sep  3 18:21:08 PDT 2016
[3608956.930675] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  367.48  Sat Sep  3 17:45:40 PDT 2016
[3608956.941606] [drm] [nvidia-drm] [GPU ID 0x00000017] Loading driver
[3608956.946046] [drm] [nvidia-drm] [GPU ID 0x00000018] Loading driver
[3608956.950253] [drm] [nvidia-drm] [GPU ID 0x00000019] Loading driver
[3608956.954408] [drm] [nvidia-drm] [GPU ID 0x0000001a] Loading driver
[3608956.958562] [drm] [nvidia-drm] [GPU ID 0x0000001b] Loading driver
[3608956.958676] [drm] [nvidia-drm] [GPU ID 0x0000001c] Loading driver
[3608956.958781] [drm] [nvidia-drm] [GPU ID 0x0000001d] Loading driver
[3608956.958942] [drm] [nvidia-drm] [GPU ID 0x0000001e] Loading driver
[3608968.848770] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceDestroyFaultInfo
[3608968.848773] nvidia_uvm: Unknown symbol nvUvmInterfaceDestroyFaultInfo (err -22)
[3608968.848798] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceInitFaultInfo
[3608968.848799] nvidia_uvm: Unknown symbol nvUvmInterfaceInitFaultInfo (err -22)
[3608969.954438] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceDestroyFaultInfo
[3608969.960128] nvidia_uvm: Unknown symbol nvUvmInterfaceDestroyFaultInfo (err -22)
[3608969.965331] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceInitFaultInfo
[3608969.970714] nvidia_uvm: Unknown symbol nvUvmInterfaceInitFaultInfo (err -22)
[3608971.212683] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceDestroyFaultInfo
[3608971.217774] nvidia_uvm: Unknown symbol nvUvmInterfaceDestroyFaultInfo (err -22)
[3608971.222498] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceInitFaultInfo
[3608971.227236] nvidia_uvm: Unknown symbol nvUvmInterfaceInitFaultInfo (err -22)
[3608972.316592] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceDestroyFaultInfo
[3608972.324298] nvidia_uvm: Unknown symbol nvUvmInterfaceDestroyFaultInfo (err -22)
[3608972.331433] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceInitFaultInfo
[3608972.338919] nvidia_uvm: Unknown symbol nvUvmInterfaceInitFaultInfo (err -22)
[3608973.640208] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceDestroyFaultInfo
[3608973.644131] nvidia_uvm: Unknown symbol nvUvmInterfaceDestroyFaultInfo (err -22)
[3608973.647635] nvidia_uvm: disagrees about version of symbol nvUvmInterfaceInitFaultInfo
[3608973.651219] nvidia_uvm: Unknown symbol nvUvmInterfaceInitFaultInfo (err -22)
NVRM: make sure that this kernel module and all NVIDIA driver
```

**Comment by tschaffter** [comment]
In `/var/log/messages` when running `nvidia-smi`:
```
Mar 22 10:35:39 ip-172-31-49-74 kernel: NVRM: API mismatch: the client has the version 375.39, but#012NVRM: this kernel module has the version 367.48.  Please#012NVRM: make sure that this kernel module and all NVIDIA driver#012NVRM: components have the same version.
```

**Comment by tschaffter** [comment]
On SoftLayer (bm03):

Drivers version: 367.48

```
3 yum list nvidia-kmod*
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Installed Packages
nvidia-kmod.x86_64
```

Version matches.

**Comment by tschaffter** [comment]
Check that the version of the drivers and the kernel module are consistent on the main inference machines.

## Test
```
nvidia-smi | grep NVIDIA-SMI && yum list nvidia-kmod*
```
## Instances
- [ ] p28x03
- [ ] p28x04
- [ ] p28x05
- [ ] p28x06
- [ ] p28x07
- [ ] p28x08
- [ ] p28x09
- [ ] p28x10
- [ ] p28x11
- [ ] p28x12

**Comment by tschaffter** [comment]
Ok, so let's investigate the issue from scratch.

# CUDA and NVIDIA driver installed
## SoftLayer
After `yum update`:
```
# nvidia-smi | grep NVIDIA-SMI && yum list nvidia-kmod*
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Installed Packages
nvidia-kmod.x86_64                                                            1:367.48-2.el7                                                            @cuda-8-0-local
```
Everything seems alright and there are no related errors in `/var/log/messages`

## AWS Leaderboard Inference machines (legacy)
On p28x12, which is the last machine configured from the initial batch of ten inference machines.

```
# nvidia-smi | grep NVIDIA-SMI && yum list nvidia-kmod*
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Installed Packages
nvidia-kmod.x86_64                                                          1:367.48-2.el7                                                           @cuda-8-0-local
```

Everything seems fine.

## Let's install a new machine as a legacy one
On p28x22:

```
# git clone https://gist.github.com/6fc1e2144fbbf59e90cad1999c0be70d.git /root/install/gist
# git log
# git checkout a5677f4b48f1c4a41fed95b22b259b79cd4d9475
```
After the first reboot (after installing CUDA but before installing the NVIDIA driver), nvidia-smi is responding fine. According to one of my comments in the startup file, it seems that CUDA installer is also installing the driver. I comment the additional installation of the NVIDIA driver and run the startup script a second time to finalize the setup. CUDA examples compile fine and after reboot, `nvidia-smi` is responding.

**Comment by tschaffter** [comment]
This issue has been solved. All the instances are running the same CUDA and NVIDIA drivers.
